export const categories = [
  { categoryId: 'starters', categoryName: 'Starters', displayOrder: 1, isActive: true },
  { categoryId: 'main-course', categoryName: 'Main Course', displayOrder: 2, isActive: true },
  { categoryId: 'drinks', categoryName: 'Drinks', displayOrder: 3, isActive: true },
  { categoryId: 'sweets', categoryName: 'Sweets', displayOrder: 4, isActive: true },
];

export const items = [
  {
    itemId: 'samosa-01',
    categoryId: 'starters',
    itemName: 'Aloo Samosa',
    description: 'Crispy potato samosas served hot.',
    price: 35,
    imageUrl: 'https://via.placeholder.com/280x180.png?text=Aloo+Samosa',
    vegType: 'veg',
    isAvailable: true,
    displayOrder: 1,
  },
  {
    itemId: 'paneer-tikka-01',
    categoryId: 'starters',
    itemName: 'Paneer Tikka',
    description: 'Grilled cottage cheese with spices.',
    price: 180,
    imageUrl: 'https://via.placeholder.com/280x180.png?text=Paneer+Tikka',
    vegType: 'veg',
    isAvailable: true,
    displayOrder: 2,
  },
  {
    itemId: 'butter-chicken-01',
    categoryId: 'main-course',
    itemName: 'Butter Chicken',
    description: 'Creamy chicken curry with butter masala.',
    price: 280,
    imageUrl: 'https://via.placeholder.com/280x180.png?text=Butter+Chicken',
    vegType: 'non-veg',
    isAvailable: true,
    displayOrder: 1,
  },
  {
    itemId: 'veg-biryani-01',
    categoryId: 'main-course',
    itemName: 'Veg Biryani',
    description: 'Aromatic rice cooked with vegetables.',
    price: 220,
    imageUrl: 'https://via.placeholder.com/280x180.png?text=Veg+Biryani',
    vegType: 'veg',
    isAvailable: false,
    displayOrder: 2,
  },
  {
    itemId: 'masala-chai-01',
    categoryId: 'drinks',
    itemName: 'Masala Chai',
    description: 'Hot spiced tea brewed fresh.',
    price: 30,
    imageUrl: 'https://via.placeholder.com/280x180.png?text=Masala+Chai',
    vegType: 'veg',
    isAvailable: true,
    displayOrder: 1,
  },
  {
    itemId: 'gulab-jamun-01',
    categoryId: 'sweets',
    itemName: 'Gulab Jamun',
    description: 'Soft milk dumplings in sugar syrup.',
    price: 120,
    imageUrl: 'https://via.placeholder.com/280x180.png?text=Gulab+Jamun',
    vegType: 'veg',
    isAvailable: true,
    displayOrder: 1,
  },
];
